spring: 
  profiles: 
    active: 
    - dev
---
server:
  port:8001 #注册中心占用7001端口，冒号后面必须要有空格 
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSourece
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.techic.springcloud.entities
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml

eureka: 
  clinet: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
      